version: '3.7'
services:
  backend:
    build: ./backend
    image: h15t3r5im5/backend:latest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp


  frontend:
    build: ./frontend
    image: h15t3r5im5/frontend:latest
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - backend


  mysql:
    build: ./mysql
    image: h15t3r5im5/clinic-db:latest
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_ROOT_PASSWORD: root   
      

  nginx:
    build: ./nginx
    image: h15t3r5im5/nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - backend 
    - frontend   