apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: h15t3r5im5/backend
        ports:
          - containerPort: 9966

---

apiVersion: v1
kind: Service
metadata:
   name: backend
   labels:
     app: backend      
spec:
   ports:
     - protocol: TCP
       port: 9966
       targetPort: 9966
   selector:
     app: backend
